service: easyexpress-backend
configValidationMode: error
frameworkVersion: '3.32'

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-bundle

custom:
  bundle:
    linting: false
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name
  customDomain:
    domainName: api.apiservice.live
    stage: ${self:provider.stage}
    basePath: 'v1'
    certificateName: apiservice.live
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ca-central-1
  stage: prod
  memorySize: 128
  timeout: 10
  endpointType: regional
  environment:
    REGION: ca-central-1
    FROM_EMAIL: mengzhouaws@gmail.com
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail 
          Resource: '*'
functions:
  send-email:
    handler: api/send-email.handler
    description: send email
    events:
      - http:
          path: /email
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
   
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
